import xdfAxios from '@/sdk/xdf-axios';

// mw 的token
// let token = 'gr_user_id=cd204b4d-b9ab-41ff-89b2-77907bfeecb8; Hm_lvt_a2d66dc97f8a8c5600c3356fcf5136e9=1699161583,1699799662,1700026263,1700489027; a773a5312dd88294_gr_session_id=0cd74460-5e8a-4cbf-9bac-9fa93579d270; a773a5312dd88294_gr_session_id_sent_vst=0cd74460-5e8a-4cbf-9bac-9fa93579d270; MK_UC_ROOMBOX=ZmRkODQ3MWMtOGI2Yy00ZTk3LTg5ODAtMTc3MzE3OTY3Y2Ji; MK_MS_ROOMBOX=MjExODIxZmMtMDc2NC00YzA4LWE0Y2ItNmI3ODQzMGFjZGM0; CurrentMeikeSystemMainOrg=10000; CurrentMeikeSystemSubOrg=10003815';

// 白木的token
let token = 'Hm_lvt_a2d66dc97f8a8c5600c3356fcf5136e9=1699161583,1699799662,1700026263,1700489027; MK_UC_ROOMBOX=YzI2NDg2NzgtZTM5MS00MDQ1LWJiMDQtMGU4ZmViMjA2YjI5; gr_user_id=423c98b9-e4ba-4b9d-a2f6-1b803c38147f; a773a5312dd88294_gr_session_id=b6aaf949-d931-468e-9306-becbaf936b8d; a773a5312dd88294_gr_session_id_sent_vst=b6aaf949-d931-468e-9306-becbaf936b8d; MK_MS_ROOMBOX=YWY2MzJlZGYtZjQwMi00MTY2LTkzNDktODAyODU2Mjk3MDQy; CurrentMeikeSystemMainOrg=10000; CurrentMeikeSystemSubOrg=10000454';

// let title1 = "G8暑-物理";
let obj1 = {
	"code":200,
	"data":{
		"list":[
			{
				"assistantNumber":"",
				"assistants":[],
				"audiencePreEnterTime":30,
				"auditNumber":0,
				"channel":0,
				"channelName":"后台自建",
				"classCode":"RBXGH2WA6P1",
				"classId":213199,
				"classroomEnName":"",
				"classroomId":3194729,
				"classroomName":"臻臻G7-目标 第1讲",
				"classroomStatus":2,
				"clientVersion":2,
				"courseWareNumber":"",
				"definitionDesc":"标清",
				"deleteAble":false,
				"deptId":301,
				"deptName":"海淀分部",
				"duration":120,
				"endTime":"2023-08-01 21:00",
				"extendTime":1440,
				"fakeLive":false,
				"id":3194729,
				"lessonId":"3194729",
				"level":0,
				"mainId":3194729,
				"managerNumber":"",
				"orgName":"臻臻",
				"organizationId":10000454,
				"parentId":0,
				"resourceNum":7,
				"startTime":"2023-08-01 19:00",
				"studentNumber":76,
				"tagIdList":[],
				"tagIds":"",
				"tagName":"",
				"tagNames":"",
				"teacher":{
					"createTime":"",
					"email":"",
					"id":2207,
					"isInClass":"",
					"joinTime":"",
					"leaveTime":"",
					"mainOrgId":"",
					"nickname":"臻臻老师",
					"organizationId":"",
					"phone":"156****5244",
					"realName":"",
					"relatedUsers":"",
					"roleId":"",
					"status":"",
					"studentCode":"",
					"updateTime":"",
					"userId":2207,
					"userName":"meike9919dvf13q"
				},
				"templateId":1,
				"wallFormat":"1V2-6"
			},
			{
				"assistantNumber":"",
				"assistants":[],
				"audiencePreEnterTime":30,
				"auditNumber":0,
				"channel":0,
				"channelName":"后台自建",
				"classCode":"RBXGH2WA6P1",
				"classId":213199,
				"classroomEnName":"",
				"classroomId":3194732,
				"classroomName":"臻臻G7-目标 第2讲",
				"classroomStatus":2,
				"clientVersion":2,
				"courseWareNumber":"",
				"definitionDesc":"标清",
				"deleteAble":false,
				"deptId":301,
				"deptName":"海淀分部",
				"duration":120,
				"endTime":"2023-08-02 21:00",
				"extendTime":1440,
				"fakeLive":false,
				"id":3194732,
				"lessonId":"3194732",
				"level":0,
				"mainId":3194732,
				"managerNumber":"",
				"orgName":"臻臻",
				"organizationId":10000454,
				"parentId":0,
				"resourceNum":6,
				"startTime":"2023-08-02 19:00",
				"studentNumber":76,
				"tagIdList":[],
				"tagIds":"",
				"tagName":"",
				"tagNames":"",
				"teacher":{
					"createTime":"",
					"email":"",
					"id":2207,
					"isInClass":"",
					"joinTime":"",
					"leaveTime":"",
					"mainOrgId":"",
					"nickname":"臻臻老师",
					"organizationId":"",
					"phone":"156****5244",
					"realName":"",
					"relatedUsers":"",
					"roleId":"",
					"status":"",
					"studentCode":"",
					"updateTime":"",
					"userId":2207,
					"userName":"meike9919dvf13q"
				},
				"templateId":1,
				"wallFormat":"1V2-6"
			},
			{
				"assistantNumber":"",
				"assistants":[],
				"audiencePreEnterTime":30,
				"auditNumber":0,
				"channel":0,
				"channelName":"后台自建",
				"classCode":"RBXGH2WA6P1",
				"classId":213199,
				"classroomEnName":"",
				"classroomId":3194735,
				"classroomName":"臻臻G7-目标 第3讲",
				"classroomStatus":2,
				"clientVersion":2,
				"courseWareNumber":"",
				"definitionDesc":"标清",
				"deleteAble":false,
				"deptId":301,
				"deptName":"海淀分部",
				"duration":120,
				"endTime":"2023-08-03 21:00",
				"extendTime":1440,
				"fakeLive":false,
				"id":3194735,
				"lessonId":"3194735",
				"level":0,
				"mainId":3194735,
				"managerNumber":"",
				"orgName":"臻臻",
				"organizationId":10000454,
				"parentId":0,
				"resourceNum":7,
				"startTime":"2023-08-03 19:00",
				"studentNumber":75,
				"tagIdList":[],
				"tagIds":"",
				"tagName":"",
				"tagNames":"",
				"teacher":{
					"createTime":"",
					"email":"",
					"id":2207,
					"isInClass":"",
					"joinTime":"",
					"leaveTime":"",
					"mainOrgId":"",
					"nickname":"臻臻老师",
					"organizationId":"",
					"phone":"156****5244",
					"realName":"",
					"relatedUsers":"",
					"roleId":"",
					"status":"",
					"studentCode":"",
					"updateTime":"",
					"userId":2207,
					"userName":"meike9919dvf13q"
				},
				"templateId":1,
				"wallFormat":"1V2-6"
			},
			{
				"assistantNumber":"",
				"assistants":[],
				"audiencePreEnterTime":30,
				"auditNumber":0,
				"channel":0,
				"channelName":"后台自建",
				"classCode":"RBXGH2WA6P1",
				"classId":213199,
				"classroomEnName":"",
				"classroomId":3194738,
				"classroomName":"臻臻G7-目标 第4讲",
				"classroomStatus":2,
				"clientVersion":2,
				"courseWareNumber":"",
				"definitionDesc":"标清",
				"deleteAble":false,
				"deptId":301,
				"deptName":"海淀分部",
				"duration":120,
				"endTime":"2023-08-04 21:00",
				"extendTime":1440,
				"fakeLive":false,
				"id":3194738,
				"lessonId":"3194738",
				"level":0,
				"mainId":3194738,
				"managerNumber":"",
				"orgName":"臻臻",
				"organizationId":10000454,
				"parentId":0,
				"resourceNum":7,
				"startTime":"2023-08-04 19:00",
				"studentNumber":75,
				"tagIdList":[],
				"tagIds":"",
				"tagName":"",
				"tagNames":"",
				"teacher":{
					"createTime":"",
					"email":"",
					"id":2207,
					"isInClass":"",
					"joinTime":"",
					"leaveTime":"",
					"mainOrgId":"",
					"nickname":"臻臻老师",
					"organizationId":"",
					"phone":"156****5244",
					"realName":"",
					"relatedUsers":"",
					"roleId":"",
					"status":"",
					"studentCode":"",
					"updateTime":"",
					"userId":2207,
					"userName":"meike9919dvf13q"
				},
				"templateId":1,
				"wallFormat":"1V2-6"
			},
			{
				"assistantNumber":"",
				"assistants":[],
				"audiencePreEnterTime":30,
				"auditNumber":0,
				"channel":0,
				"channelName":"后台自建",
				"classCode":"RBXGH2WA6P1",
				"classId":213199,
				"classroomEnName":"",
				"classroomId":3194816,
				"classroomName":"臻臻G7-目标 第5讲",
				"classroomStatus":2,
				"clientVersion":2,
				"courseWareNumber":"",
				"definitionDesc":"标清",
				"deleteAble":false,
				"deptId":301,
				"deptName":"海淀分部",
				"duration":120,
				"endTime":"2023-08-07 21:00",
				"extendTime":1440,
				"fakeLive":false,
				"id":3194816,
				"lessonId":"3194816",
				"level":0,
				"mainId":3194816,
				"managerNumber":"",
				"orgName":"臻臻",
				"organizationId":10000454,
				"parentId":0,
				"resourceNum":6,
				"startTime":"2023-08-07 19:00",
				"studentNumber":75,
				"tagIdList":[],
				"tagIds":"",
				"tagName":"",
				"tagNames":"",
				"teacher":{
					"createTime":"",
					"email":"",
					"id":2207,
					"isInClass":"",
					"joinTime":"",
					"leaveTime":"",
					"mainOrgId":"",
					"nickname":"臻臻老师",
					"organizationId":"",
					"phone":"156****5244",
					"realName":"",
					"relatedUsers":"",
					"roleId":"",
					"status":"",
					"studentCode":"",
					"updateTime":"",
					"userId":2207,
					"userName":"meike9919dvf13q"
				},
				"templateId":1,
				"wallFormat":"1V2-6"
			},
			{
				"assistantNumber":"",
				"assistants":[],
				"audiencePreEnterTime":30,
				"auditNumber":0,
				"channel":0,
				"channelName":"后台自建",
				"classCode":"RBXGH2WA6P1",
				"classId":213199,
				"classroomEnName":"",
				"classroomId":3194819,
				"classroomName":"臻臻G7-目标 第6讲",
				"classroomStatus":2,
				"clientVersion":2,
				"courseWareNumber":"",
				"definitionDesc":"标清",
				"deleteAble":false,
				"deptId":301,
				"deptName":"海淀分部",
				"duration":120,
				"endTime":"2023-08-08 21:00",
				"extendTime":1440,
				"fakeLive":false,
				"id":3194819,
				"lessonId":"3194819",
				"level":0,
				"mainId":3194819,
				"managerNumber":"",
				"orgName":"臻臻",
				"organizationId":10000454,
				"parentId":0,
				"resourceNum":6,
				"startTime":"2023-08-08 19:00",
				"studentNumber":75,
				"tagIdList":[],
				"tagIds":"",
				"tagName":"",
				"tagNames":"",
				"teacher":{
					"createTime":"",
					"email":"",
					"id":2207,
					"isInClass":"",
					"joinTime":"",
					"leaveTime":"",
					"mainOrgId":"",
					"nickname":"臻臻老师",
					"organizationId":"",
					"phone":"156****5244",
					"realName":"",
					"relatedUsers":"",
					"roleId":"",
					"status":"",
					"studentCode":"",
					"updateTime":"",
					"userId":2207,
					"userName":"meike9919dvf13q"
				},
				"templateId":1,
				"wallFormat":"1V2-6"
			},
			{
				"assistantNumber":"",
				"assistants":[],
				"audiencePreEnterTime":30,
				"auditNumber":0,
				"channel":0,
				"channelName":"后台自建",
				"classCode":"RBXGH2WA6P1",
				"classId":213199,
				"classroomEnName":"",
				"classroomId":3194822,
				"classroomName":"臻臻G7-目标 第7讲",
				"classroomStatus":2,
				"clientVersion":2,
				"courseWareNumber":"",
				"definitionDesc":"标清",
				"deleteAble":false,
				"deptId":301,
				"deptName":"海淀分部",
				"duration":120,
				"endTime":"2023-08-09 21:00",
				"extendTime":1440,
				"fakeLive":false,
				"id":3194822,
				"lessonId":"3194822",
				"level":0,
				"mainId":3194822,
				"managerNumber":"",
				"orgName":"臻臻",
				"organizationId":10000454,
				"parentId":0,
				"resourceNum":6,
				"startTime":"2023-08-09 19:00",
				"studentNumber":75,
				"tagIdList":[],
				"tagIds":"",
				"tagName":"",
				"tagNames":"",
				"teacher":{
					"createTime":"",
					"email":"",
					"id":2207,
					"isInClass":"",
					"joinTime":"",
					"leaveTime":"",
					"mainOrgId":"",
					"nickname":"臻臻老师",
					"organizationId":"",
					"phone":"156****5244",
					"realName":"",
					"relatedUsers":"",
					"roleId":"",
					"status":"",
					"studentCode":"",
					"updateTime":"",
					"userId":2207,
					"userName":"meike9919dvf13q"
				},
				"templateId":1,
				"wallFormat":"1V2-6"
			},
			{
				"assistantNumber":"",
				"assistants":[],
				"audiencePreEnterTime":30,
				"auditNumber":0,
				"channel":0,
				"channelName":"后台自建",
				"classCode":"RBXGH2WA6P1",
				"classId":213199,
				"classroomEnName":"",
				"classroomId":3194825,
				"classroomName":"臻臻G7-目标 第8讲",
				"classroomStatus":2,
				"clientVersion":2,
				"courseWareNumber":"",
				"definitionDesc":"标清",
				"deleteAble":false,
				"deptId":301,
				"deptName":"海淀分部",
				"duration":120,
				"endTime":"2023-08-10 21:00",
				"extendTime":1440,
				"fakeLive":false,
				"id":3194825,
				"lessonId":"3194825",
				"level":0,
				"mainId":3194825,
				"managerNumber":"",
				"orgName":"臻臻",
				"organizationId":10000454,
				"parentId":0,
				"resourceNum":6,
				"startTime":"2023-08-10 19:00",
				"studentNumber":75,
				"tagIdList":[],
				"tagIds":"",
				"tagName":"",
				"tagNames":"",
				"teacher":{
					"createTime":"",
					"email":"",
					"id":2207,
					"isInClass":"",
					"joinTime":"",
					"leaveTime":"",
					"mainOrgId":"",
					"nickname":"臻臻老师",
					"organizationId":"",
					"phone":"156****5244",
					"realName":"",
					"relatedUsers":"",
					"roleId":"",
					"status":"",
					"studentCode":"",
					"updateTime":"",
					"userId":2207,
					"userName":"meike9919dvf13q"
				},
				"templateId":1,
				"wallFormat":"1V2-6"
			},
			{
				"assistantNumber":"",
				"assistants":[],
				"audiencePreEnterTime":30,
				"auditNumber":0,
				"channel":0,
				"channelName":"后台自建",
				"classCode":"RBXGH2WA6P1",
				"classId":213199,
				"classroomEnName":"",
				"classroomId":3194828,
				"classroomName":"臻臻G7-目标 第9讲",
				"classroomStatus":2,
				"clientVersion":2,
				"courseWareNumber":"",
				"definitionDesc":"标清",
				"deleteAble":false,
				"deptId":301,
				"deptName":"海淀分部",
				"duration":120,
				"endTime":"2023-08-11 21:00",
				"extendTime":1440,
				"fakeLive":false,
				"id":3194828,
				"lessonId":"3194828",
				"level":0,
				"mainId":3194828,
				"managerNumber":"",
				"orgName":"臻臻",
				"organizationId":10000454,
				"parentId":0,
				"resourceNum":8,
				"startTime":"2023-08-11 19:00",
				"studentNumber":75,
				"tagIdList":[],
				"tagIds":"",
				"tagName":"",
				"tagNames":"",
				"teacher":{
					"createTime":"",
					"email":"",
					"id":2207,
					"isInClass":"",
					"joinTime":"",
					"leaveTime":"",
					"mainOrgId":"",
					"nickname":"臻臻老师",
					"organizationId":"",
					"phone":"156****5244",
					"realName":"",
					"relatedUsers":"",
					"roleId":"",
					"status":"",
					"studentCode":"",
					"updateTime":"",
					"userId":2207,
					"userName":"meike9919dvf13q"
				},
				"templateId":1,
				"wallFormat":"1V2-6"
			},
			{
				"assistantNumber":"",
				"assistants":[],
				"audiencePreEnterTime":30,
				"auditNumber":0,
				"channel":0,
				"channelName":"后台自建",
				"classCode":"RBXGH2WA6P1",
				"classId":213199,
				"classroomEnName":"",
				"classroomId":3194741,
				"classroomName":"臻臻G7-目标 第10讲",
				"classroomStatus":2,
				"clientVersion":2,
				"courseWareNumber":"",
				"definitionDesc":"标清",
				"deleteAble":false,
				"deptId":301,
				"deptName":"海淀分部",
				"duration":120,
				"endTime":"2023-08-12 21:00",
				"extendTime":1440,
				"fakeLive":false,
				"id":3194741,
				"lessonId":"3194741",
				"level":0,
				"mainId":3194741,
				"managerNumber":"",
				"orgName":"臻臻",
				"organizationId":10000454,
				"parentId":0,
				"resourceNum":8,
				"startTime":"2023-08-12 19:00",
				"studentNumber":75,
				"tagIdList":[],
				"tagIds":"",
				"tagName":"",
				"tagNames":"",
				"teacher":{
					"createTime":"",
					"email":"",
					"id":2207,
					"isInClass":"",
					"joinTime":"",
					"leaveTime":"",
					"mainOrgId":"",
					"nickname":"臻臻老师",
					"organizationId":"",
					"phone":"156****5244",
					"realName":"",
					"relatedUsers":"",
					"roleId":"",
					"status":"",
					"studentCode":"",
					"updateTime":"",
					"userId":2207,
					"userName":"meike9919dvf13q"
				},
				"templateId":1,
				"wallFormat":"1V2-6"
			}
		],
		"total":10
	},
	"msg":""
}


// 设置cookie
const setCookie = (cookie) => {
    cookie = cookie || cookieMock;
    let arr = cookie.split('; ');
    arr.forEach(it => {
        document.cookie = it;
    })
}


// 获取url
// let _data = [
//     { title: title1, list: obj1.data.list },
//     { title: title2, list: obj2.data.list },
// ]
let data = obj1.data.list;

const getData = (callback, that) => {
    setCookie(token);

    _.forEach(data, (item, ind) => {
        xdfAxios({
            url: `/nms/ms/classroom/video/url/${item.lessonId}`,
            method: 'get'
        }).then(res => {
            res = res.data;
            let url = res.data.url;
            data[ind].url = url;
        });
    })

    setTimeout(() => {
        if (callback) {
            callback(data)
        }
    }, 2000)
}


export { getData };